#------------------------------------------------------------------------------
# Program Name: C1.3.proc_NC_emissions.R
# Author(s): Jon Seibert, Rachel Hoesly
# Date Last Modified: August 19, 2015
# Program Purpose: To fill out missing sections in the process emissions database
# Input Files: Master_Fuel_Sector_List.xlsx, C.[em]_NC_emissions_db.csv, A.NC_activity.csv
# Output Files:  C.[em]_NC_emissions.csv
# Notes:
# TODO:
#-------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# 0. Read in global settings and headers
# Define PARAM_DIR as the location of the CEDS "parameters" directory, relative
# to the "input" directory.
    PARAM_DIR <- if("input" %in% dir()) "code/parameters/" else "../code/parameters/"

# Call standard script header function to read in universal header files -
# provide logging, file support, and system functions - and start the script log.
    headers <- c( "data_functions.R" ) # Additional function files required.
    log_msg <- "Integration of process emissions data" # First message to be printed to the log
    script_name <- "C1.3.proc_NC_emissions.R"

    source( paste0( PARAM_DIR, "header.R" ) )
    initialize( script_name, log_msg, headers )

# ------------------------------------------------------------------------------
# 1. Read in files

args_from_makefile <- commandArgs( TRUE )
em <- args_from_makefile[ 1 ]
if ( is.na( em ) ) em <- "NH3"

MSL <- readData( "MAPPINGS", "Master_Fuel_Sector_List", ".xlsx", sheet_selection = "Sectors" )

MCL <- readData( "MAPPINGS", "Master_Country_List" )

activity_data <- readData( "MED_OUT", "A.NC_activity" )

emissions_data <- readData( "MED_OUT", paste0( "C.", em, "_", "NC", "_emissions_db" ), meta = FALSE )

# ----------------------------------------------------------------------------
# 2. Populate missing sectors and countries:
#    Add rows of all 0 for every missing iso/sector combination

emissions_iso_list <- unique( emissions_data$iso )
activity_iso_list <- unique( activity_data$iso )
iso_list <- activity_iso_list

# List of all non-combustion sectors
sector_list <- unique( MSL$sector[ MSL$activity != "Energy_Combustion" ] )

for( country in emissions_iso_list ){
    if( !( country %in% activity_iso_list ) ){
        iso_list <- c( iso_list, country )
    }
}

# Define indices for the start and end of the data section ( the Xyears columns )
data_start <- findDataStart( emissions_data )
data_end <- length( emissions_data )

sect_one_unit <- activity_data$units[ activity_data$sector == sector_list[ 1 ] ][ 1 ]

# Get list of iso codes missing from the emissions data
missing_iso_list <- iso_list[ iso_list %!in% emissions_iso_list ]

# Add countries missing sectors to the missing iso list
for( country in emissions_iso_list ){
    sectors_present <- unlist( emissions_data[ emissions_data$iso == country, "sector" ] )
    if( length( sectors_present ) != length( sector_list ) ){
        missing_iso_list <- c( missing_iso_list, country )
    }
}

# Create empty data frame to hold new entries
missing_entries <- emissions_data[ emissions_data$iso == "No such iso", ]

# Append a block with all missing isos for each sector
for( sector_name in sector_list ){

    # Data frame of only ID columns
    blank <- data.frame(
      iso = missing_iso_list,
      sector = sector_name,
      fuel = "process",
      units = 'kt' )

    # Add data columns of all 0
    blank <- cbind( blank, emissions_data[ 1:nrow( blank ), data_start:length( emissions_data ) ] )
    blank[ data_start:length( blank ) ] <- 0

    emissions_data <- rbind( emissions_data,blank )
}

# Remove duplicate rows generated by adding countries with sectors missing to the "missing" list
duplicates <- duplicated( emissions_data[ 1:( data_start - 1 ) ] ) # Do not include units in this
emissions_data <- emissions_data[ !duplicates, ]


# remove extra island nations not flagged to be in final data (IN MCL)
final_iso <- MCL[which(MCL$final_data_flag == 1),'iso']
emissions_data <- emissions_data[which( emissions_data$iso %in% final_iso),]

# Sort results by iso, sector, and then fuel
emissions_data <- emissions_data[ with( emissions_data, order( iso, sector, fuel ) ), ]

# At this point, the form of the data should match exactly with A.NC_activity.csv.
# If it does not, the subsequent scripts will not work.


# ------------------------------------------------------------------------------
# 4. Output
writeData(emissions_data, domain = "MED_OUT", fn = paste0( "C.", em, "_NC_emissions" ), meta = TRUE )

logStop()
# END
