#------------------------------------------------------------------------------
# Program Name: Combine_Problem_Scaling_Factors.R
# Author: Jon Seibert
# Last Updated: January 19, 2016
# Program Purpose: To combine the problem scaling factor files generated by module F.
# Input Files: *_Problem_Scaling_Factors_*.csv
# Output Files: Problem_Scaling_Factors_all.csv
# Functions Defined:
# Notes:
# TODO:
# ------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# 0. Read in global settings and headers
# Define PARAM_DIR as the location of the CEDS "parameters" directory, relative
# to the "input" directory.
    PARAM_DIR <- if("input" %in% dir()) "code/parameters/" else "../code/parameters/"

# Call standard script header function to read in universal header files -
# provide logging, file support, and system functions - and start the script log.
  headers <- c( "data_functions.R" ) # Additional function files required.
  log_msg <- paste0( "Combining problematic scaling factors files" ) # First message to be printed to the log
  script_name <- "Combine_Problem_Scaling_Factors.R"

  source( paste0( PARAM_DIR, "header.R" ) )
  initialize( script_name, log_msg, headers )

# ------------------------------------------------------------------------------------
# 1. Input

path <- "../diagnostic-output"

fn_list <- list.files(path, pattern = paste0('Problem_Scaling_Factors') )

# Prevent including previous runs' output or metadata files in the list
fn_list <- fn_list[ -grep("metadata",fn_list) ]
if( file.exists( "../diagnostic-output/Problem_Scaling_Factors_all.csv" ) ){
    fn_list <- fn_list[ -grep("all",fn_list) ]
}

fn_list_sans_ext <- c()
for( fn in fn_list ){
    fn_list_sans_ext <- c( fn_list_sans_ext, substr( fn, 1, nchar( fn ) - 4 ) )
}

file_list <- lapply( fn_list_sans_ext, readData, domain = "DIAG_OUT"  )

# ------------------------------------------------------------------------------------
# 2. Combining

i <- 1
# output <- subset( file_list[[ 1 ]], iso == "" )
output <- file_list[[ 1 ]][ 1, ]
output$emission <- ""
output$inventory <- ""
output <- subset( output, output$emission == "none" )

for( problem_file in file_list ){
    input <- problem_file

    fn <- fn_list_sans_ext[ i ]

    split_fn <- strsplit( fn, ".", fixed = TRUE )[[ 1 ]][ 2 ]
    em_species <- strsplit( split_fn, "_", fixed = TRUE )[[ 1 ]][ 1 ]

    split_fn <- strsplit( split_fn, "_", fixed = TRUE )[[ 1 ]]
    inv <- split_fn[ length( split_fn ) ]

    input$emission <- em_species
    input$inventory <- inv

    output <- rbind( output, input )
    i <- i + 1
}

# Sort output
output <- output[ with( output, order( iso, scaling_sector, year, emission, inventory ) ), ]

# ------------------------------------------------------------------------------------
# 3. Output

writeData( output, domain = "DIAG_OUT", fn = "Problem_Scaling_Factors_all" )

logStop()
# END
