#------------------------------------------------------------------------------
# Program Name: D1.1.default_emissions.R
# Author(s): Jon Seibert, Tyler Pitkanen, Rachel Hoesly, Andrea Mott
# Date Last Modified: Nov 9 2021
# Program Purpose: Reads in emissions factors (EFs) and historical fuel
#                      consumption data to calculate historical emissions.
# Input Files: A.final_comb_activity_modern.csv, B.[em]_default_EF.csv,
#               A.NC.activity.csv, C.[em],_NC_EF.csv
# Output Files: D.[em]_default_comb_emissions.csv, D.[em]_default_total_emissions.csv,
#               D.[em]_default_total_EF.csv, D.[em_default_nc_emissions.csv
# Notes: Reads in emission species from Makefile. If running in R, specify
#            emission species by changing the value of default_em_species
# TODO:
#-------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# 0. Read in global settings and headers
# Define PARAM_DIR as the location of the CEDS "parameters" directory, relative
# to the "input" directory.
    PARAM_DIR <- if("input" %in% dir()) "code/parameters/" else "../code/parameters/"

# Call standard script header function to read in universal header files -
# provide logging, file support, and system functions - and start the script log.
    headers <- c( "data_functions.R", "analysis_functions.R" ) # Additional function files required.
    log_msg <- "Calculation of default historical emissions from default emissions factors and
                energy data" # First message to be printed to the log
    script_name <- "D1.1.default_emissions.R"

    source( paste0( PARAM_DIR, "header.R" ) )
    initialize( script_name, log_msg, headers )

# Define Em Species
    args_from_makefile <- commandArgs( TRUE )
    em <- args_from_makefile[ 1 ]
    if ( is.na( em ) ) em <- 'SO2'

# ------------------------------------------------------------------------------
# 1. Read in files

comb_energy_data <- readData( "MED_OUT", "A.final_comb_activity_modern" )
comb_ef_data  <- readData( "MED_OUT", paste0("B.", em, "_comb_EF_db" ) )

nc_energy_data <- readData( "MED_OUT", "A.NC_activity" )
nc_ef_data  <- readData( "MED_OUT", paste0("C.", em, "_NC_EF" ) )


# Check input files for correct naming
printLog( "Checking energy and combustion data" )
fuelCheck( comb_energy_data )
fuelCheck( comb_ef_data  )
sectorCheck( comb_energy_data )
sectorCheck( comb_ef_data  )

printLog( "Checking non-combustion data" )
fuelCheck( nc_energy_data )
fuelCheck( nc_ef_data  )
sectorCheck( nc_energy_data )
sectorCheck( nc_ef_data  )

# ------------------------------------------------------------------------------
# 2. Define Functions

# Function to calculate default emissions data from driver data and emissions factors
calculateEmissions <- function( drivers, efs ){

#   # DEBUG
#   drivers <- comb_energy_data
#   efs <- comb_ef_data

  # # Required to get full list of names
  # source( paste( PARAM_DIR, "common_data.R", sep = "" ) )

  # Ensure data is in numeric form to avoid errors
  data_start <- findDataStart( efs )
  efs[ data_start:length( efs ) ] <-
    sapply( efs[ data_start:length( efs ) ], as.numeric )
  drivers[ data_start:length( drivers ) ] <-
    sapply( drivers[ data_start:length( drivers ) ], as.numeric )

  # Combine datasets for easier calculation
  merged_data <- merge( drivers, efs, by = c("iso","sector","fuel"),
                        all = TRUE, suffixes = c(".a",".b") )

  driver_cols <- paste0( X_emissions_years, ".a" )
  ef_cols <- paste0( X_emissions_years, ".b" )

  # Multiply driver data by ef data to generate default emissions
  emissions_nums <- merged_data[ driver_cols ] * merged_data[ ef_cols ]

  # Set all NAs generated by merge-expansion to 0
  emissions_nums[ is.na( emissions_nums ) ] <- 0

  # Unit multiplication for calculation: worry about simplification later.
  merged_data$units <- paste0( merged_data$units.a, "*", merged_data$units.b )

  # If the ef units was NA, replace the multiplied unit with only the driver unit.
  # NA units treated as unitless for this purpose, as any data with NA units has
  # already been set to 0.
  merged_data$units[ is.na( merged_data$units.b ) ] <- merged_data$units.a[ is.na( merged_data$units.b ) ]

  id_cols <- merged_data[ c( "iso", "sector", "fuel", "units" ) ]

  emissions_data <- cbind( id_cols, emissions_nums )
  names( emissions_data ) <- c( "iso", "sector", "fuel", "units", X_emissions_years )

  return( emissions_data )
}

# ------------------------------------------------------------------------------
# 2. Calculate Emissions
# Use the formula: Emissions = Fuel_Consumption * Fuel_Emissions_Factor

printLog( "Calculating emissions data" )

# # Ensure ef data is in numeric form to avoid errors
# efs_data_start <- findDataStart( comb_ef_data )
# comb_ef_data[ efs_data_start:length( comb_ef_data ) ] <-
    # sapply( comb_ef_data[ efs_data_start:length( comb_ef_data ) ], as.numeric )


# Employ function to calculate default emissions
comb_emissions <- calculateEmissions( comb_energy_data, comb_ef_data )
nc_emissions <- calculateEmissions( nc_energy_data, nc_ef_data )

# Add additional emissions to existing sectors
    # (these are emissions that are not added in mod A activity data, since the system is set up
    # where  1 sector = 1 activity data. )
    # TODO: if this need to occur frequently, functionalize or create
    #                 separate script to add together sub-sectors to create sectors.

    # Add sintering to nc_emissions.
        # Below adds together pig iron (calculated with the activity data)
        # and sintering emissions (calculated separately in module C) to from the
        # 2C1_Iron-steel-alloy-prod sector.
        #TODO: potentially make this into it's own script

        # Read in sintering data
        # Note: sintering data only exists for SO2, NOx, and CO.However, for SO2,
        # some iron-steel isos have user added emissions data, and are therefore removed.
        if(em %in% c("NOx","CO","SO2")){

            sintering_emissions <- readData("MED_OUT",paste0( "C.", em, "_sintering_emissions"))
            sintering_emissions <- sintering_emissions %>% select(-c(paste0("X", 1750:1959)))

            # Remove sintering emissions that have user-added iron-steel emissions

                # Create dataframe of iso-sectors that have user-added emissions data
                user_added_emissions_df <- readData('DEFAULT_EF_IN', domain_extension = 'non-combustion-emissions/',
                                                    paste0('C.',em,'_NC_emissions_user_added'))

                # Organize user-added emissions data, filter for iron-steel
                user_added_emissions_iso_sector <- user_added_emissions_df %>%
                  select(iso, sector) %>%
                  filter(sector == "2C1_Iron-steel-alloy-prod") %>%
                  dplyr::rename(iso2 = iso) %>%
                  dplyr::rename(sector2 = sector)

                if (nrow(user_added_emissions_iso_sector) > 0){
                  user_added_emissions_iso_sector <- user_added_emissions_iso_sector %>% mutate(sector = "sintering")

                  # Remove iso-sectors from EF dataframe that have user added emissions
                  sintering_emissions <- sintering_emissions %>%
                      anti_join(user_added_emissions_iso_sector, by = c("iso" = "iso2", "sector" = "sector2"))

                  # Write warning for those iso-sectors removed:
                  overlap <- sintering_emissions %>%
                    semi_join(user_added_emissions_iso_sector, by = c("iso" = "iso2", "sector" = "sector2"))
                  if (nrow(overlap) >0){
                    warning("The following isos user added emissions are removed since they correspond to user-added emissions:",
                            paste0(overlap$iso,", ",overlap$sector, "; "))
                  }
                }

            # Combine sintering emissions with 2C1 in nc_emissions.
            pig_iron_emissions <- nc_emissions %>%
              filter(sector == "2C1_Iron-steel-alloy-prod")
            iron_steel_sector <- rbind(pig_iron_emissions, sintering_emissions)
            iron_steel_emissions <- iron_steel_sector %>%
              group_by(iso, units, fuel) %>%
              summarize_if(is.numeric, sum, na.rm  = TRUE) %>%
              mutate(sector = "2C1_Iron-steel-alloy-prod") %>%
              select(iso, sector, units, fuel, everything())
            nc_emissions <- filter(nc_emissions, sector != "2C1_Iron-steel-alloy-prod")

            # recombine 2C1 with nc emissions
            nc_emissions <- rbind(data.frame(nc_emissions), data.frame(iron_steel_emissions))
            nc_emissions <- nc_emissions[order(nc_emissions$iso),]
        }

# -----------------------------------------------------------------------------
# 3. Recalculate Emission Factors

new_nc_ef <- calculate_EFs(activity_data = nc_energy_data,
                           emissions_data = nc_emissions %>% mutate(units = 'kt'))
new_comb_ef <- calculate_EFs(activity_data = comb_energy_data,
                             emissions_data = comb_emissions %>% mutate(units = 'kt'))


# Combine total emissions and total ef
total_emissions <- rbind(comb_emissions, nc_emissions)
total_efs <- rbind(new_comb_ef, new_nc_ef)

# -----------------------------------------------------------------------------
# 4. Output
# Add comments for each table
comments.emissions <- c( paste0( "Default ", em, "emissions" ),
    paste0( " by intermediate sector, intermediate fuel, historical year,",
            " from default emissions factors" ) )
comments.efs <- c( paste0( "Default ", em, "efs" ),
                         paste0( " by intermediate sector, intermediate fuel, historical year.") )

# write tables as CSV files
writeData( total_emissions, domain = "MED_OUT", fn = paste0( "D.", em, "_default_total_emissions" ),
    comments = comments.emissions )
writeData( total_efs, domain = "MED_OUT", fn = paste0( "D.", em, "_default_total_EF" ),
           comments = comments.efs )

writeData( comb_emissions, domain = "MED_OUT", fn = paste0( "D.", em, "_default_comb_emissions" ),
           comments = comments.emissions )
writeData( nc_emissions, domain = "MED_OUT", fn = paste0( "D.", em, "_default_nc_emissions" ),
           comments = comments.emissions )

# Every script should finish with this line
logStop()

# END
