#------------------------------------------------------------------------------
# Program Name: D1.1.default_comb_emissions.R
# Author(s): Jon Seibert, Tyler Pitkanen
# Date Last Modified: June 16, 2015
# Program Purpose: Reads in emissions factors (EFs) and historical fuel 
#                      consumption data to calculate historical emissions. 
# Input Files: A.comb_activity.csv, B.[em]_default_EF.csv
# Output Files: D.[em]_default_comb_emissions.csv
# Notes: Reads in emission species from Makefile. If running in R, specify
#            emission species by changing the value of default_em_species
# TODO: 
#-------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# 0. Read in global settings and headers

# Before we can load headers we need some paths defined. They may be provided by
#   a system environment variable or may have already been set in the workspace.
# Set variable PARAM_DIR to be the data system directory
    dirs <- paste0( unlist( strsplit( getwd(), c( '/', '\\' ), fixed = T ) ), '/' )
    for ( i in 1:length( dirs ) ) {
        setwd( paste( dirs[ 1:( length( dirs ) + 1 - i ) ], collapse = '' ) )
        wd <- grep( 'CEDS/input', list.dirs(), value = T )
        if ( length(wd) > 0 ) {
            setwd( wd[1] )
            break
        }
    }
    PARAM_DIR <- "../code/parameters/"

# Call standard script header function to read in universal header files - 
# provide logging, file support, and system functions - and start the script log.
    headers <- c( "data_functions.R", "analysis_functions.R" ) # Additional function files required.
    log_msg <- "Calculation of default historical emissions from default emissions factors and 
                energy data" # First message to be printed to the log
    script_name <- "D1.1.default_comb_emissions.R"
    
    source( paste0( PARAM_DIR, "header.R" ) )
    initialize( script_name, log_msg, headers )

# ------------------------------------------------------------------------------
# 1. Read in files

# Pass in emissions species via make file
printLog( "Reading in emission species" )
args_from_makefile <- commandArgs( TRUE )
em_species <- args_from_makefile[1]

# Use a default species if not running via "make" (ie if running in R directly)
# default_em_species <- "SO2"
default_em_species <- "BC"

if ( is.na( em_species ) == TRUE ) {
    printLog( paste( "Emission species not specified in make.",
                     "Using default species:", default_em_species ) )
    em_species <- default_em_species
}

energy_data <- readData( "MED_OUT", "A.comb_activity" )
ef_data  <- readData( "MED_OUT", paste0("B.", em_species, "_comb_EF_db" ) )

# Check input files for correct naming
fuelCheck( energy_data )
fuelCheck( ef_data  )
sectorCheck( energy_data )
sectorCheck( ef_data  )

# ------------------------------------------------------------------------------
# 2. Calculate Emissions
# Use the formula: Emissions = Fuel_Consumption * Fuel_Emissions_Factor

printLog( "Calculating emissions data" )

# # Ensure ef data is in numeric form to avoid errors
# efs_data_start <- findDataStart( ef_data )
# ef_data[ efs_data_start:length( ef_data ) ] <- 
    # sapply( ef_data[ efs_data_start:length( ef_data ) ], as.numeric )

# Function to calculate default emissions data from energy data and emissions factors
calculateEmissions <- function( drivers, efs ){

    # # DEBUG
    # drivers <- energy_data
    # efs <- ef_data

    # # Required to get full list of names
    # source( paste( PARAM_DIR, "common_data.R", sep = "" ) )

    # Ensure data is in numeric form to avoid errors
    data_start <- findDataStart( efs )
    efs[ data_start:length( efs ) ] <- 
        sapply( efs[ data_start:length( efs ) ], as.numeric )
    drivers[ data_start:length( drivers ) ] <- 
        sapply( drivers[ data_start:length( drivers ) ], as.numeric )
    
    # Combine datasets for easier calculation
    merged_data <- merge( drivers, efs, by = c("iso","sector","fuel"), 
                          all = TRUE, suffixes = c(".a",".b") )
    
    driver_cols <- paste0( X_emissions_years, ".a" )
    ef_cols <- paste0( X_emissions_years, ".b" )
    
    # Multiply driver data by ef data to generate default emissions
    emissions_nums <- merged_data[ driver_cols ] * merged_data[ ef_cols ]
    
    # Set all NAs generated by merge-expansion to 0
    emissions_nums[ is.na( emissions_nums ) ] <- 0
    
    # Unit multiplication for calcuation: worry about simplification later.
    merged_data$units <- paste0( merged_data$units.a, "*", merged_data$units.b )
    
    # If the ef units was NA, replace the multiplied unit with only the driver unit.
    # NA units treated as unitless for this purpose, as any data with NA units has
    # already been set to 0.
    merged_data$units[ is.na( merged_data$units.b ) ] <- merged_data$units.a[ is.na( merged_data$units.b ) ]
    
    id_cols <- merged_data[ c( "iso", "sector", "fuel", "units" ) ]
    
    emissions_data <- cbind( id_cols, emissions_nums )
    names( emissions_data ) <- c( "iso", "sector", "fuel", "units", X_emissions_years )  
    
    return( emissions_data )
}

# Employ function to calculate default emissions
emissions <- calculateEmissions( energy_data, ef_data )

# # Match the fuel data to their respective emissions factors
# num_data_cols <- sapply( energy_data, is.numeric )
# num_EF_cols   <- sapply( ef_data,  is.numeric )
# energy_data_num <- energy_data[ , num_data_cols ]
# ef_data_num  <- ef_data[ , num_EF_cols ]

# # Calculate emissions for each year, sector, and fuel    
# emissions_num <- energy_data_num * ef_data_num
# emissions <- cbind( energy_data[, 1:4 ], emissions_num )
# names( emissions ) <- names( energy_data )

# # ##Compare world totals for coal, petroleum
# # world_totals <- aggregate( emissions[ , num_data_cols ], by = list( 
    # # emissions$fuel ), sum ) 
# # names( world_totals ) <- c( "fuel", names( energy_data_num ) )
# # num_row <- gsub( "[^0-9]", "", names( world_totals ) )
# # names( num_row ) <- names( world_totals )
# # world_totals_ext <- rbind( num_row, world_totals )


# -----------------------------------------------------------------------------
# 3. Output
# Add comments for each table
comments.emissions <- c( paste0( "Default ", em_species, "comb emissions" ), 
    paste0( " by intermediate sector, intermediate fuel, historical year,",
            " from default emissions factors" ) )
                                            
# write tables as CSV files
writeData( emissions, domain = "MED_OUT", fn = paste0( "D.", em_species, "_default_comb_emissions" ), 
    comments = comments.emissions )

# Every script should finish with this line
logStop()

# END
