#------------------------------------------------------------------------------
# Program Name: D1.1.default_emissions.R
# Author(s): Jon Seibert, Tyler Pitkanen, Rachel Hoesly
# Date Last Modified: Feb 1 2016
# Program Purpose: Reads in emissions factors (EFs) and historical fuel
#                      consumption data to calculate historical emissions.
# Input Files: A.final_comb_activity_modern.csv, B.[em]_default_EF.csv
# Output Files: D.[em]_default_comb_emissions.csv
# Notes: Reads in emission species from Makefile. If running in R, specify
#            emission species by changing the value of default_em_species
# TODO:
#-------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# 0. Read in global settings and headers
# Define PARAM_DIR as the location of the CEDS "parameters" directory, relative
# to the "input" directory.
    PARAM_DIR <- if("input" %in% dir()) "code/parameters/" else "../code/parameters/"

# Call standard script header function to read in universal header files -
# provide logging, file support, and system functions - and start the script log.
    headers <- c( "data_functions.R", "analysis_functions.R" ) # Additional function files required.
    log_msg <- "Calculation of default historical emissions from default emissions factors and
                energy data" # First message to be printed to the log
    script_name <- "D1.1.default_emissions.R"

    source( paste0( PARAM_DIR, "header.R" ) )
    initialize( script_name, log_msg, headers )

# Define Em Species
    args_from_makefile <- commandArgs( TRUE )
    em <- args_from_makefile[ 1 ]
    if ( is.na( em ) ) em <- 'CO2'

# ------------------------------------------------------------------------------
# 1. Read in files

comb_energy_data <- readData( "MED_OUT", "A.final_comb_activity_modern" )
comb_ef_data  <- readData( "MED_OUT", paste0("B.", em, "_comb_EF_db" ) )

nc_energy_data <- readData( "MED_OUT", "A.NC_activity" )
nc_ef_data  <- readData( "MED_OUT", paste0("C.", em, "_NC_EF" ) )


# Check input files for correct naming
printLog( "Checking energy and combustion data" )
fuelCheck( comb_energy_data )
fuelCheck( comb_ef_data  )
sectorCheck( comb_energy_data )
sectorCheck( comb_ef_data  )

printLog( "Checking non-combustion data" )
fuelCheck( nc_energy_data )
fuelCheck( nc_ef_data  )
sectorCheck( nc_energy_data )
sectorCheck( nc_ef_data  )

# ------------------------------------------------------------------------------
# 2. Define Functions

# Function to calculate default emissions data from driver data and emissions factors
calculateEmissions <- function( drivers, efs ){

#   # DEBUG
#   drivers <- comb_energy_data
#   efs <- comb_ef_data

  # # Required to get full list of names
  # source( paste( PARAM_DIR, "common_data.R", sep = "" ) )

  # Ensure data is in numeric form to avoid errors
  data_start <- findDataStart( efs )
  efs[ data_start:length( efs ) ] <-
    sapply( efs[ data_start:length( efs ) ], as.numeric )
  drivers[ data_start:length( drivers ) ] <-
    sapply( drivers[ data_start:length( drivers ) ], as.numeric )

  # Combine datasets for easier calculation
  merged_data <- merge( drivers, efs, by = c("iso","sector","fuel"),
                        all = TRUE, suffixes = c(".a",".b") )

  driver_cols <- paste0( X_emissions_years, ".a" )
  ef_cols <- paste0( X_emissions_years, ".b" )

  # Multiply driver data by ef data to generate default emissions
  emissions_nums <- merged_data[ driver_cols ] * merged_data[ ef_cols ]

  # Set all NAs generated by merge-expansion to 0
  emissions_nums[ is.na( emissions_nums ) ] <- 0

  # Unit multiplication for calcuation: worry about simplification later.
  merged_data$units <- paste0( merged_data$units.a, "*", merged_data$units.b )

  # If the ef units was NA, replace the multiplied unit with only the driver unit.
  # NA units treated as unitless for this purpose, as any data with NA units has
  # already been set to 0.
  merged_data$units[ is.na( merged_data$units.b ) ] <- merged_data$units.a[ is.na( merged_data$units.b ) ]

  id_cols <- merged_data[ c( "iso", "sector", "fuel", "units" ) ]

  emissions_data <- cbind( id_cols, emissions_nums )
  names( emissions_data ) <- c( "iso", "sector", "fuel", "units", X_emissions_years )

  return( emissions_data )
}

# ------------------------------------------------------------------------------
# 2. Calculate Emissions
# Use the formula: Emissions = Fuel_Consumption * Fuel_Emissions_Factor

printLog( "Calculating emissions data" )

# # Ensure ef data is in numeric form to avoid errors
# efs_data_start <- findDataStart( comb_ef_data )
# comb_ef_data[ efs_data_start:length( comb_ef_data ) ] <-
    # sapply( comb_ef_data[ efs_data_start:length( comb_ef_data ) ], as.numeric )


# Employ function to calculate default emissions
comb_emissions <- calculateEmissions( comb_energy_data, comb_ef_data )

nc_emissions <- calculateEmissions( nc_energy_data, nc_ef_data )

# Combine total emissions and total ef
total_emissions <- rbind(comb_emissions, nc_emissions)
total_efs <- rbind(comb_ef_data, nc_ef_data)

# -----------------------------------------------------------------------------
# 3. Output
# Add comments for each table
comments.emissions <- c( paste0( "Default ", em, "emissions" ),
    paste0( " by intermediate sector, intermediate fuel, historical year,",
            " from default emissions factors" ) )
comments.efs <- c( paste0( "Default ", em, "efs" ),
                         paste0( " by intermediate sector, intermediate fuel, historical year.") )

# write tables as CSV files
writeData( total_emissions, domain = "MED_OUT", fn = paste0( "D.", em, "_default_total_emissions" ),
    comments = comments.emissions )
writeData( total_efs, domain = "MED_OUT", fn = paste0( "D.", em, "_default_total_EF" ),
           comments = comments.efs )

writeData( comb_emissions, domain = "MED_OUT", fn = paste0( "D.", em, "_default_comb_emissions" ),
           comments = comments.emissions )
writeData( nc_emissions, domain = "MED_OUT", fn = paste0( "D.", em, "_default_nc_emissions" ),
           comments = comments.emissions )



# Every script should finish with this line
logStop()

# END
